# This workflow will compress the files in a zip and upload them to the school release

on:
  push:
    branches: main
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compress files
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
        run: |
          zip plumed-school-benchmark.zip *.md *.zip
          gh release upload School plumed-school-benchmark.zip
